//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameStore.WebUI.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GameStore.WebUI.App_LocalResources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Account_Login_Login {
            get {
                return ResourceManager.GetString("Account_Login_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Account_Register_Register {
            get {
                return ResourceManager.GetString("Account_Register_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string AllGamesViewModel_Date {
            get {
                return ResourceManager.GetString("AllGamesViewModel_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string AllGamesViewModel_Name {
            get {
                return ResourceManager.GetString("AllGamesViewModel_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string AllGamesViewModel_Price {
            get {
                return ResourceManager.GetString("AllGamesViewModel_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort.
        /// </summary>
        public static string AllGamesViewModel_Sort {
            get {
                return ResourceManager.GetString("AllGamesViewModel_Sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 day.
        /// </summary>
        public static string BanUserDisplayOption_Day {
            get {
                return ResourceManager.GetString("BanUserDisplayOption_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 hour.
        /// </summary>
        public static string BanUserDisplayOption_Hour {
            get {
                return ResourceManager.GetString("BanUserDisplayOption_Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 month.
        /// </summary>
        public static string BanUserDisplayOption_Month {
            get {
                return ResourceManager.GetString("BanUserDisplayOption_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permanent.
        /// </summary>
        public static string BanUserDisplayOption_Permanent {
            get {
                return ResourceManager.GetString("BanUserDisplayOption_Permanent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 week.
        /// </summary>
        public static string BanUserDisplayOption_Week {
            get {
                return ResourceManager.GetString("BanUserDisplayOption_Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place game to basket.
        /// </summary>
        public static string BasketConfirmationDialog_Title {
            get {
                return ResourceManager.GetString("BasketConfirmationDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer.
        /// </summary>
        public static string Comment_Comments_Answer {
            get {
                return ResourceManager.GetString("Comment_Comments_Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ban.
        /// </summary>
        public static string Comment_Comments_Ban {
            get {
                return ResourceManager.GetString("Comment_Comments_Ban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quote.
        /// </summary>
        public static string Comment_Comments_Quote {
            get {
                return ResourceManager.GetString("Comment_Comments_Quote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body.
        /// </summary>
        public static string CommentViewModel_Body {
            get {
                return ResourceManager.GetString("CommentViewModel_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string CommentViewModel_Name {
            get {
                return ResourceManager.GetString("CommentViewModel_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply filter.
        /// </summary>
        public static string Common_Apply {
            get {
                return ResourceManager.GetString("Common_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basket.
        /// </summary>
        public static string Common_Basket {
            get {
                return ResourceManager.GetString("Common_Basket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string Common_Comment {
            get {
                return ResourceManager.GetString("Common_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string Common_Comments {
            get {
                return ResourceManager.GetString("Common_Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Common_Create {
            get {
                return ResourceManager.GetString("Common_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Common_Delete {
            get {
                return ResourceManager.GetString("Common_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Common_Edit {
            get {
                return ResourceManager.GetString("Common_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game.
        /// </summary>
        public static string Common_Game {
            get {
                return ResourceManager.GetString("Common_Game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games.
        /// </summary>
        public static string Common_Games {
            get {
                return ResourceManager.GetString("Common_Games", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genre.
        /// </summary>
        public static string Common_Genre {
            get {
                return ResourceManager.GetString("Common_Genre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genres.
        /// </summary>
        public static string Common_Genres {
            get {
                return ResourceManager.GetString("Common_Genres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string Common_No {
            get {
                return ResourceManager.GetString("Common_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string Common_Order {
            get {
                return ResourceManager.GetString("Common_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        public static string Common_Orders {
            get {
                return ResourceManager.GetString("Common_Orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay.
        /// </summary>
        public static string Common_Pay {
            get {
                return ResourceManager.GetString("Common_Pay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platform.
        /// </summary>
        public static string Common_Platform {
            get {
                return ResourceManager.GetString("Common_Platform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platforms.
        /// </summary>
        public static string Common_Platforms {
            get {
                return ResourceManager.GetString("Common_Platforms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publisher.
        /// </summary>
        public static string Common_Publisher {
            get {
                return ResourceManager.GetString("Common_Publisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publishers.
        /// </summary>
        public static string Common_Publishers {
            get {
                return ResourceManager.GetString("Common_Publishers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string Common_Role {
            get {
                return ResourceManager.GetString("Common_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string Common_Roles {
            get {
                return ResourceManager.GetString("Common_Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Common_Select {
            get {
                return ResourceManager.GetString("Common_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string Common_User {
            get {
                return ResourceManager.GetString("Common_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Common_Users {
            get {
                return ResourceManager.GetString("Common_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Common_Yes {
            get {
                return ResourceManager.GetString("Common_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent genre.
        /// </summary>
        public static string CreateGenreViewModel_ParentGenre {
            get {
                return ResourceManager.GetString("CreateGenreViewModel_ParentGenre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two years.
        /// </summary>
        public static string DateFilterOption_2Years {
            get {
                return ResourceManager.GetString("DateFilterOption_2Years", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Three years.
        /// </summary>
        public static string DateFilterOption_3Years {
            get {
                return ResourceManager.GetString("DateFilterOption_3Years", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string DateFilterOption_All {
            get {
                return ResourceManager.GetString("DateFilterOption_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One month.
        /// </summary>
        public static string DateFilterOption_Month {
            get {
                return ResourceManager.GetString("DateFilterOption_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One week.
        /// </summary>
        public static string DateFilterOption_Week {
            get {
                return ResourceManager.GetString("DateFilterOption_Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One year.
        /// </summary>
        public static string DateFilterOption_Year {
            get {
                return ResourceManager.GetString("DateFilterOption_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete this comment?.
        /// </summary>
        public static string DeleteCommentModal_Body {
            get {
                return ResourceManager.GetString("DeleteCommentModal_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete comment.
        /// </summary>
        public static string DeleteCommentModal_Title {
            get {
                return ResourceManager.GetString("DeleteCommentModal_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Game_AllGames_ApplyFilter {
            get {
                return ResourceManager.GetString("Game_AllGames_ApplyFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy.
        /// </summary>
        public static string Game_AllGames_Buy {
            get {
                return ResourceManager.GetString("Game_AllGames_Buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Game_AllGames_ClearFilter {
            get {
                return ResourceManager.GetString("Game_AllGames_ClearFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted.
        /// </summary>
        public static string Game_AllGames_Deleted {
            get {
                return ResourceManager.GetString("Game_AllGames_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string Game_AllGames_Download {
            get {
                return ResourceManager.GetString("Game_AllGames_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New game.
        /// </summary>
        public static string Game_New_NewGame {
            get {
                return ResourceManager.GetString("Game_New_NewGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update game.
        /// </summary>
        public static string Game_Update_UpdateGame {
            get {
                return ResourceManager.GetString("Game_Update_UpdateGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum.
        /// </summary>
        public static string GamesByPriceFilterViewModel_Maximum {
            get {
                return ResourceManager.GetString("GamesByPriceFilterViewModel_Maximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum.
        /// </summary>
        public static string GamesByPriceFilterViewModel_Minimum {
            get {
                return ResourceManager.GetString("GamesByPriceFilterViewModel_Minimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorting.
        /// </summary>
        public static string GameSortingViewModel_Sort {
            get {
                return ResourceManager.GetString("GameSortingViewModel_Sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date published.
        /// </summary>
        public static string GameViewModel_DatePublished {
            get {
                return ResourceManager.GetString("GameViewModel_DatePublished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string GameViewModel_Description {
            get {
                return ResourceManager.GetString("GameViewModel_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discontinued.
        /// </summary>
        public static string GameViewModel_Discontinued {
            get {
                return ResourceManager.GetString("GameViewModel_Discontinued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key.
        /// </summary>
        public static string GameViewModel_Key {
            get {
                return ResourceManager.GetString("GameViewModel_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string GameViewModel_Name {
            get {
                return ResourceManager.GetString("GameViewModel_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string GameViewModel_Price {
            get {
                return ResourceManager.GetString("GameViewModel_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units in stock.
        /// </summary>
        public static string GameViewModel_UnitsInStock {
            get {
                return ResourceManager.GetString("GameViewModel_UnitsInStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string GameViewModelBuilder_OtherGenre {
            get {
                return ResourceManager.GetString("GameViewModelBuilder_OtherGenre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string GameViewModelBuilder_UnknownPublisher {
            get {
                return ResourceManager.GetString("GameViewModelBuilder_UnknownPublisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New genre.
        /// </summary>
        public static string Genre_Create_NewGenre {
            get {
                return ResourceManager.GetString("Genre_Create_NewGenre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add subgenre.
        /// </summary>
        public static string Genre_Genres_AddSubgenre {
            get {
                return ResourceManager.GetString("Genre_Genres_AddSubgenre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update genre.
        /// </summary>
        public static string Genre_Update_UpdateGenre {
            get {
                return ResourceManager.GetString("Genre_Update_UpdateGenre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string GenreViewModel_Name {
            get {
                return ResourceManager.GetString("GenreViewModel_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guid.
        /// </summary>
        public static string IBoxTerminalPaymentViewModel_Guid {
            get {
                return ResourceManager.GetString("IBoxTerminalPaymentViewModel_Guid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice.
        /// </summary>
        public static string IBoxTerminalPaymentViewModel_Invoice {
            get {
                return ResourceManager.GetString("IBoxTerminalPaymentViewModel_Invoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum.
        /// </summary>
        public static string IBoxTerminalPaymentViewModel_Sum {
            get {
                return ResourceManager.GetString("IBoxTerminalPaymentViewModel_Sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string ItemsPerPageDisplayItem_All {
            get {
                return ResourceManager.GetString("ItemsPerPageDisplayItem_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string Languages_English {
            get {
                return ResourceManager.GetString("Languages_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukrainian.
        /// </summary>
        public static string Languages_Ukrainian {
            get {
                return ResourceManager.GetString("Languages_Ukrainian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string LoginViewModel_Email {
            get {
                return ResourceManager.GetString("LoginViewModel_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string LoginViewModel_Password {
            get {
                return ResourceManager.GetString("LoginViewModel_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me?.
        /// </summary>
        public static string LoginViewModel_RememberMe {
            get {
                return ResourceManager.GetString("LoginViewModel_RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string NameFilter_GameTitle {
            get {
                return ResourceManager.GetString("NameFilter_GameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make order.
        /// </summary>
        public static string Order_Basket_MakeOrder {
            get {
                return ResourceManager.GetString("Order_Basket_MakeOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Axis Bank offers internet banking services, personal banking services including accounts, cards, loans, investment options to personals, corporates and NRIs..
        /// </summary>
        public static string Order_Details_BankDescription {
            get {
                return ResourceManager.GetString("Order_Details_BankDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank.
        /// </summary>
        public static string Order_Details_BankTitle {
            get {
                return ResourceManager.GetString("Order_Details_BankTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change shipper.
        /// </summary>
        public static string Order_Details_ChangeShipper {
            get {
                return ResourceManager.GetString("Order_Details_ChangeShipper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paying via iBox you save time to visit bank branch and receive the opportunity to make payments on a round-the-clock basis..
        /// </summary>
        public static string Order_Details_IBoxDescription {
            get {
                return ResourceManager.GetString("Order_Details_IBoxDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBox terminal.
        /// </summary>
        public static string Order_Details_IBoxTitle {
            get {
                return ResourceManager.GetString("Order_Details_IBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As a premier payments technology company, Visa’s global network connects thousands of financial institutions with millions of merchants and cardholders every day..
        /// </summary>
        public static string Order_Details_VisaDescription {
            get {
                return ResourceManager.GetString("Order_Details_VisaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visa.
        /// </summary>
        public static string Order_Details_VisaTitle {
            get {
                return ResourceManager.GetString("Order_Details_VisaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string Order_History_Filter {
            get {
                return ResourceManager.GetString("Order_History_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders history.
        /// </summary>
        public static string Order_History_OrdersHistory {
            get {
                return ResourceManager.GetString("Order_History_OrdersHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipped.
        /// </summary>
        public static string Order_Orders_Shipped {
            get {
                return ResourceManager.GetString("Order_Orders_Shipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBox terminal.
        /// </summary>
        public static string Order_PayWithIBox_IBox {
            get {
                return ResourceManager.GetString("Order_PayWithIBox_IBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VISA.
        /// </summary>
        public static string Order_PayWithVisa_Visa {
            get {
                return ResourceManager.GetString("Order_PayWithVisa_Visa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipper.
        /// </summary>
        public static string Order_Shipper_Shipper {
            get {
                return ResourceManager.GetString("Order_Shipper_Shipper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount.
        /// </summary>
        public static string OrderDetailsViewModel_Discount {
            get {
                return ResourceManager.GetString("OrderDetailsViewModel_Discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string OrderDetailsViewModel_Price {
            get {
                return ResourceManager.GetString("OrderDetailsViewModel_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string OrderDetailsViewModel_Quantity {
            get {
                return ResourceManager.GetString("OrderDetailsViewModel_Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date.
        /// </summary>
        public static string OrdersHistoryViewModel_EndDate {
            get {
                return ResourceManager.GetString("OrdersHistoryViewModel_EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date.
        /// </summary>
        public static string OrdersHistoryViewModel_StartDate {
            get {
                return ResourceManager.GetString("OrdersHistoryViewModel_StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items per page.
        /// </summary>
        public static string PagingViewModel_ItemsPerPage {
            get {
                return ResourceManager.GetString("PagingViewModel_ItemsPerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New publisher.
        /// </summary>
        public static string Publisher_New_NewPublisher {
            get {
                return ResourceManager.GetString("Publisher_New_NewPublisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update publisher.
        /// </summary>
        public static string Publisher_Update_UpdatePublisher {
            get {
                return ResourceManager.GetString("Publisher_Update_UpdatePublisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company name.
        /// </summary>
        public static string PublisherViewModel_CompanyName {
            get {
                return ResourceManager.GetString("PublisherViewModel_CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string PublisherViewModel_Description {
            get {
                return ResourceManager.GetString("PublisherViewModel_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home page.
        /// </summary>
        public static string PublisherViewModel_HomePage {
            get {
                return ResourceManager.GetString("PublisherViewModel_HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string RegisterViewModel_ConfirmPassword {
            get {
                return ResourceManager.GetString("RegisterViewModel_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string RegisterViewModel_Email {
            get {
                return ResourceManager.GetString("RegisterViewModel_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        public static string RegisterViewModel_Name {
            get {
                return ResourceManager.GetString("RegisterViewModel_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string RegisterViewModel_Password {
            get {
                return ResourceManager.GetString("RegisterViewModel_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create role.
        /// </summary>
        public static string Role_New_CreateRole {
            get {
                return ResourceManager.GetString("Role_New_CreateRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System role.
        /// </summary>
        public static string Role_Roles_System {
            get {
                return ResourceManager.GetString("Role_Roles_System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User defined role.
        /// </summary>
        public static string Role_Roles_UserRole {
            get {
                return ResourceManager.GetString("Role_Roles_UserRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update role.
        /// </summary>
        public static string Role_Update_UpdateRole {
            get {
                return ResourceManager.GetString("Role_Update_UpdateRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game store.
        /// </summary>
        public static string Shared_Layout_GameStore {
            get {
                return ResourceManager.GetString("Shared_Layout_GameStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Shared_Layout_Login {
            get {
                return ResourceManager.GetString("Shared_Layout_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Shared_Layout_Logout {
            get {
                return ResourceManager.GetString("Shared_Layout_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders history.
        /// </summary>
        public static string Shared_Layout_OrdersHistory {
            get {
                return ResourceManager.GetString("Shared_Layout_OrdersHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Shared_Layout_Register {
            get {
                return ResourceManager.GetString("Shared_Layout_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company name.
        /// </summary>
        public static string ShipperViewModel_CompanyName {
            get {
                return ResourceManager.GetString("ShipperViewModel_CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string ShipperViewModel_Phone {
            get {
                return ResourceManager.GetString("ShipperViewModel_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most commented.
        /// </summary>
        public static string SortDisplayOption_MostCommented {
            get {
                return ResourceManager.GetString("SortDisplayOption_MostCommented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most viewed.
        /// </summary>
        public static string SortDisplayOption_MostViewed {
            get {
                return ResourceManager.GetString("SortDisplayOption_MostViewed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string SortDisplayOption_New {
            get {
                return ResourceManager.GetString("SortDisplayOption_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price asc.
        /// </summary>
        public static string SortDisplayOption_PriceAsc {
            get {
                return ResourceManager.GetString("SortDisplayOption_PriceAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price desc.
        /// </summary>
        public static string SortDisplayOption_PriceDesc {
            get {
                return ResourceManager.GetString("SortDisplayOption_PriceDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent genre.
        /// </summary>
        public static string UpdateGenreViewModel_ParentGenre {
            get {
                return ResourceManager.GetString("UpdateGenreViewModel_ParentGenre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ban user.
        /// </summary>
        public static string User_Ban_Ban {
            get {
                return ResourceManager.GetString("User_Ban_Ban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change role.
        /// </summary>
        public static string User_ChangeRole_ChangeRole {
            get {
                return ResourceManager.GetString("User_ChangeRole_ChangeRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign publisher.
        /// </summary>
        public static string User_Details_AssignPublisher {
            get {
                return ResourceManager.GetString("User_Details_AssignPublisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ban user.
        /// </summary>
        public static string User_Details_Ban {
            get {
                return ResourceManager.GetString("User_Details_Ban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banned.
        /// </summary>
        public static string User_Details_Banned {
            get {
                return ResourceManager.GetString("User_Details_Banned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change role.
        /// </summary>
        public static string User_Details_ChangeRole {
            get {
                return ResourceManager.GetString("User_Details_ChangeRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unban.
        /// </summary>
        public static string User_Details_Unban {
            get {
                return ResourceManager.GetString("User_Details_Unban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        public static string UserViewModel_CreatedAt {
            get {
                return ResourceManager.GetString("UserViewModel_CreatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string UserViewModel_Email {
            get {
                return ResourceManager.GetString("UserViewModel_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        public static string UserViewModel_Name {
            get {
                return ResourceManager.GetString("UserViewModel_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card holders name.
        /// </summary>
        public static string VisaPaymentViewModel_CardHolder {
            get {
                return ResourceManager.GetString("VisaPaymentViewModel_CardHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration month.
        /// </summary>
        public static string VisaPaymentViewModel_CardMonth {
            get {
                return ResourceManager.GetString("VisaPaymentViewModel_CardMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card number.
        /// </summary>
        public static string VisaPaymentViewModel_CardNumber {
            get {
                return ResourceManager.GetString("VisaPaymentViewModel_CardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration year.
        /// </summary>
        public static string VisaPaymentViewModel_CardYear {
            get {
                return ResourceManager.GetString("VisaPaymentViewModel_CardYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CVV2.
        /// </summary>
        public static string VisaPaymentViewModel_CVV2 {
            get {
                return ResourceManager.GetString("VisaPaymentViewModel_CVV2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email .
        /// </summary>
        public static string VisaPaymentViewModel_Email {
            get {
                return ResourceManager.GetString("VisaPaymentViewModel_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone .
        /// </summary>
        public static string VisaPaymentViewModel_Phone {
            get {
                return ResourceManager.GetString("VisaPaymentViewModel_Phone", resourceCulture);
            }
        }
    }
}
