//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Data.Entity;
using System.Data.Entity.Infrastructure;

namespace GameStore.Domain.NorthwindDb
{
	public partial class NorthwindEntities : BaseDataContext
    {
        public NorthwindEntities()
            : base("name=NorthwindEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual IDbSet<Category> Categories { get; set; }
        public virtual IDbSet<CustomerDemographic> CustomerDemographics { get; set; }
        public virtual IDbSet<Customer> Customers { get; set; }
        public virtual IDbSet<Employee> Employees { get; set; }
        public virtual IDbSet<Order_Detail> Order_Details { get; set; }
        public virtual IDbSet<Order> Orders { get; set; }
        public virtual IDbSet<Product> Products { get; set; }
        public virtual IDbSet<Region> Regions { get; set; }
        public virtual IDbSet<Shipper> Shippers { get; set; }
        public virtual IDbSet<Supplier> Suppliers { get; set; }
        public virtual IDbSet<Territory> Territories { get; set; }
    }
}
